export enum AlertType {
  DELIVERY_DELAY = 'DELIVERY_DELAY',
  PREPARATION_DELAY = 'PREPARATION_DELAY',
  DIETARY_RESTRICTION = 'DIETARY_RESTRICTION',
  STAFF_SHORTAGE = 'STAFF_SHORTAGE',
  OTHER = 'OTHER',
}
