export enum MealStatus {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  PREPARED = 'PREPARED',
  IN_DELIVERY = 'IN_DELIVERY',
  DELIVERED = 'DELIVERED',
  DELAYED = 'DELAYED',
  CANCELLED = 'CANCELLED',
}
